---

version: "3"

services:
  postgres:
    image: timescale/timescaledb:latest-pg11
    volumes:
      - ./priv/persistent/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    network_mode: host

  chrome:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    network_mode: host
