---

version: "3"

services:
  neon:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - "4000:4000"
    volumes:
      - ./assets/script:/opt/app/assets/script
      - ./assets/static:/opt/app/assets/static
      - ./assets/style:/opt/app/assets/style
      - ./config:/opt/app/config
      - ./lib:/opt/app/lib
      - ./priv:/opt/app/priv
      - ./test:/opt/app/test
    command: do ecto.create, phx.server
    working_dir: /opt/app
    depends_on:
      - postgres

  postgres:
    image: timescale/timescaledb:latest-pg11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
