---

name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Build_Development:
    name: Build (Development)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull
        run: docker-compose pull

      - name: Cache
        uses: satackey/action-docker-layer-caching@v0.0.8

      - name: Build
        run: docker-compose build

  Lint_Mix:
    name: Lint (Mix)
    runs-on: ubuntu-latest

    needs:
      - Build_Development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: satackey/action-docker-layer-caching@v0.0.8
        with:
          skip-save: true

      - name: Format
        run: docker-compose run neon mix format

  Lint_Credo:
    name: Lint (Credo)
    runs-on: ubuntu-latest

    needs:
      - Build_Development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: satackey/action-docker-layer-caching@v0.0.8
        with:
          skip-save: true

      - name: Lint
        run: docker-compose run neon mix credo --all

  # TODO: Enable this at some point. Maybe
  #  Lint_Dialyzer:
  #    name: Lint (Dialyzer)
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v2
  #
  #      - name: Cache
  #        uses: actions/cache@v2
  #        with:
  #          path: priv/plts
  #          key: dialyzer
  #
  #      - name: Compile
  #        run: docker-compose build
  #
  #      - name: Lint
  #        run: docker-compose run neon mix dialyzer

  Lint_Eslint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest

    needs:
      - Build_Development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: satackey/action-docker-layer-caching@v0.0.8
        with:
          skip-save: true

      - name: Generate
        run: docker-compose run neon mix absinthe.schema.json ./priv/static/schema.json

      - name: Lint
        run: docker-compose run neon npm run lint:js

  Lint_Stylelint:
    name: Lint (Stylelint)
    runs-on: ubuntu-latest

    needs:
      - Build_Development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: satackey/action-docker-layer-caching@v0.0.8
        with:
          skip-save: true

      - name: Lint
        run: docker-compose run neon npm run lint:css

  Test_Unit:
    name: Test (Unit)
    runs-on: ubuntu-latest

    needs:
      - Build_Development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: satackey/action-docker-layer-caching@v0.0.8
        with:
          skip-save: true

      - name: Test
        run: docker-compose run neon mix test.unit

  Test_Browser:
    name: Test (Browser)
    runs-on: ubuntu-latest

    needs:
      - Build_Development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: satackey/action-docker-layer-caching@v0.0.8
        with:
          skip-save: true

      - name: Build
        run: docker-compose run neon npm run build
        env:
          MIX_ENV: test

      - name: Test
        run: docker-compose run neon mix test.browser

  Build_Production:
    name: Build (Production)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build -f Dockerfile-production .
