---

name: Publish

on:
  push:
    branches:
    - master

jobs:
  Lint_Mix:
    name: Lint (Mix)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Format
        run: docker-compose run neon mix format

  Lint_Credo:
    name: Lint (Credo)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run neon mix credo --all

  # TODO: Enable this at some point. Maybe
  #  Lint_Dialyzer:
  #    name: Lint (Dialyzer)
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v2
  #
  #      - name: Cache
  #        uses: actions/cache@v2
  #        with:
  #          path: priv/plts
  #          key: dialyzer
  #
  #      - name: Compile
  #        run: docker-compose build
  #
  #      - name: Lint
  #        run: docker-compose run neon mix dialyzer

  Lint_Eslint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Generate
        run: docker-compose run neon mix absinthe.schema.json ./priv/static/schema.json

      - name: Lint
        run: docker-compose run neon npm run lint:js

  Lint_Stylelint:
    name: Lint (Stylelint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Lint
        run: docker-compose run neon npm run lint:css

  Test_Unit:
    name: Test (Unit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Test
        run: docker-compose run neon mix test.unit

  Test_Browser:
    name: Test (Browser)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Build
        run: docker-compose run neon npm run build
        env:
          MIX_ENV: test

      - name: Test
        run: docker-compose run neon mix test.browser

  Publish:
    runs-on: ubuntu-latest

    needs:
      - Lint_Mix
      - Lint_Credo
      - Lint_Eslint
      - Lint_Stylelint
      - Test_Unit
      - Test_Browser

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build -f Dockerfile-production -t docker.pkg.github.com/btkostner/neon/neon .

      - name: Publish
        run: |
          docker login -u neon -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
          docker push docker.pkg.github.com/docker.pkg.github.com/btkostner/neon/neon
