---

name: Update

on:
  schedule:
    - cron:  "0 0 * * 6"

jobs:
  Translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Extract
        run: docker-compose run neon mix gettext.extract --merge

      - name: Push
        run: |
          git config --local user.email "git@btkostner.io"
          git config --local user.name "Blake Kostner"

          git add priv/gettext
          git commit -m "l10n: update gettext templates" || echo "no changes"

          git push
